In [46]:
import streamlit as st
import pandas as pd
import numpy as np
import time

import matplotlib.pyplot as plt # plotting library
import seaborn as sns # pretty plotting

sns.set(rc={'figure.figsize':(20,10)})

from sklearn.linear_model import LinearRegression # linear regression package
from sklearn.model_selection import train_test_split # split dataset

from sklearn.linear_model import Lasso

from sklearn.linear_model import Ridge

from sklearn.metrics import mean_squared_error as mse

In [48]:
# insurance_df = pd.read_csv('insurance_regression.csv')
# housing_df = pd.read_csv('data/housing.csv').reset_index()
housing_df = pd.read_csv('data/housing.csv')
housing_df.head(20)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semifurnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semifurnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semifurnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semifurnished
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semifurnished
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semifurnished
15,9100000,6000,4,1,2,yes,no,yes,no,no,2,no,semifurnished
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished
17,8960000,8500,3,2,4,yes,no,no,no,yes,2,no,furnished
18,8890000,4600,3,2,2,yes,yes,no,no,yes,2,no,furnished
19,8855000,6420,3,2,2,yes,no,no,no,yes,1,yes,semifurnished

In [49]:
columns = ['area','bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']
target = ['price']

X = housing_df[columns]
y = housing_df[target]

X_dummies = pd.get_dummies(X)

X_final = X_dummies.drop(['mainroad_no', 'guestroom_no', 'basement_no', 'hotwaterheating_no', 'airconditioning_no', 'prefarea_no'], axis=1)

X_final.head()

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semifurnished,furnishingstatus_unfurnished
0,7420,4,2,3,2,1,0,0,0,1,1,1,0,0
1,8960,4,4,4,3,1,0,0,0,1,0,1,0,0
2,9960,3,2,2,2,1,0,1,0,0,1,0,1,0
3,7500,4,2,2,3,1,0,1,0,1,1,1,0,0
4,7420,4,1,2,2,1,1,1,0,1,0,1,0,0

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 0.3, random_state = 42)

In [51]:
model = LinearRegression()

In [52]:
model.fit(X_train, y_train)

LinearRegression()

In [53]:
print(model.score(X_test, y_test))

0.6463350878895877

In [54]:
import joblib

In [55]:
# saving the model
filename = 'model/housing_model3.sav'
joblib.dump(model, filename)

['model/housing_model3.sav']

In [56]:
loaded_model = joblib.load(filename)

In [15]:
loaded_model.predict(X_test)

array([[5372312.61614641],
       [7069241.00525807],
       [3099290.78784024],
       [4526446.61703974],
       [3281573.61192656],
       [3589455.18752547],
       [5728625.30074517],
       [6422877.52476236],
       [2797870.49568591],
       [2554357.99210551],
       [9693560.19894657],
       [2802903.76131031],
       [3026465.95300836],
       [3433891.33202092],
       [3792786.34565513],
       [5321204.36478554],
       [2999852.37322993],
       [4813306.52790376],
       [4572077.61633938],
       [3595733.80237382],
       [5605701.03333098],
       [5838934.41614982],
       [2730716.89440108],
       [4837741.37096246],
       [5638460.49223857],
       [7809681.30410655],
       [3347443.37529207],
       [5328750.6625753 ],
       [8323072.8323739 ],
       [3374792.28854334],
       [6379706.15324898],
       [3397999.89564252],
       [6709115.8233402 ],
       [4249666.18392567],
       [3594972.20315591],
       [5842994.13027721],
       [5115480.11172668],
       [4359421.90319848],
       [3046570.15372424],
       [4597379.56416964],
       [4784358.1758961 ],
       [3411743.78220679],
       [7048978.02507302],
       [4062741.36892573],
       [3785699.24160861],
       [4286017.77250844],
       [6729020.20739641],
       [4133428.23821411],
       [3845434.09183083],
       [3655159.46220357],
       [7439302.79944484],
       [2869444.70398563],
       [4468816.138304  ],
       [4474332.83085885],
       [3790094.69366283],
       [2607548.31509125],
       [7484173.67473394],
       [2912521.8376414 ],
       [4288766.92856502],
       [2768963.26950036],
       [5085040.92323164],
       [3552078.21169881],
       [5302353.24799836],
       [4231219.34966538],
       [4777666.66597256],
       [4749128.97396194],
       [7227708.34560927],
       [3547097.71091147],
       [6257007.36201451],
       [6281861.39296942],
       [4724974.20779797],
       [5111537.60350725],
       [4628387.10726123],
       [8033569.61251159],
       [3475245.27785436],
       [5465194.44654501],
       [4099826.20844264],
       [4490619.8427956 ],
       [4787230.18858056],
       [4016745.04174708],
       [7720896.40387667],
       [4213805.47198351],
       [6660115.77473413],
       [5403121.59582178],
       [2735220.76102227],
       [7105152.1027995 ],
       [2596569.15845831],
       [3751123.26669057],
       [7989380.89132851],
       [8385201.9710021 ],
       [3292999.34804883],
       [6064783.11075629],
       [3578078.47660201],
       [3715646.20395539],
       [7866539.40858856],
       [4675429.52635589],
       [5241467.95089469],
       [6408824.17914905],
       [4927283.22506899],
       [6016039.22482595],
       [4001044.18004055],
       [6543468.56266503],
       [3743701.72935291],
       [6122124.82004407],
       [5263613.65957781],
       [4427035.02710476],
       [7113024.58500312],
       [6473306.81656723],
       [6536377.59307021],
       [7153784.10673248],
       [7173099.40073649],
       [4938872.44647579],
       [3957507.77132247],
       [3254459.62826403],
       [4325743.66584545],
       [3279788.35349533],
       [2764977.26281621],
       [2284744.63243067],
       [3681692.68869109],
       [4055332.49978579],
       [3756783.55352126],
       [4960900.56796539],
       [3961010.02251466],
       [4060631.634143  ],
       [6010508.28488051],
       [2356719.15341123],
       [5620463.04275165],
       [3359695.73124726],
       [8069125.43392249],
       [6899820.48632773],
       [3334032.76681398],
       [4994371.64761068],
       [6991813.31353787],
       [6600920.56859718],
       [3229130.90303272],
       [2319097.1909621 ],
       [3170052.43901872],
       [5647944.6452336 ],
       [3096476.70963452],
       [3974934.22682986],
       [2615575.5237179 ],
       [3976282.03954354],
       [5277503.71800008],
       [4077504.4935587 ],
       [4161209.6907822 ],
       [2393816.93039445],
       [6813169.01830005],
       [5341221.01242613],
       [6847577.16463819],
       [7279768.48835278],
       [5512369.54760754],
       [4572538.51080985],
       [3812830.38534951],
       [3834646.21553009],
       [3350648.20235336],
       [7315891.39525151],
       [8107534.58411868],
       [3976263.27565867],
       [7187281.98339335],
       [3762257.20056579],
       [4093208.8446666 ],
       [7090389.28405399],
       [5459978.75336373],
       [5219643.13131587]])

In [14]:
# get coefficients
coefficient = model.coef_

# get intercept
intercept = model.intercept_

In [15]:
coefficient

array([[  261.29692414,   348.90691516,   424.11912829,  -104.81182299,
        23628.36722236,   596.05658924,   109.12197876,  -374.91224933,
         -330.26631867]])

In [16]:
intercept

array([-12865.20866928])

In [18]:
model.score(X_final, y)

0.7506272930769431

In [19]:
y_predicted = model.predict(X_test)

In [16]:
# put coefficients into dataframe
# pair the feature names with the coefficients
coefficients_pd = pd.DataFrame((list(zip(columns, model.coef_ * 1000))), columns = ['Features', 'Coefficients'])

# print table of coefficients for contribution chart
coefficients_pd

  Features                                       Coefficients
0     area  [253287.25231305338, 80893141.27100325, 111475...

In [17]:
coefficients_pd.sort_values('Coefficients').set_index('Features').plot(kind = 'barh', color = 'g')

TypeError: no numeric data to plot

In [18]:
# We input new advertising data into the model to predict future sales

# Sample TV, Radio, Newspaper
new_data = [[10, 30, 100]]
model.predict(new_data)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 13 is different from 3)

In [14]:
!pip install pipreqs

Requirement already satisfied: pipreqs in c:\programdata\anaconda3\lib\site-packages (0.4.11)
Requirement already satisfied: docopt in c:\programdata\anaconda3\lib\site-packages (from pipreqs) (0.6.2)
Requirement already satisfied: yarg in c:\programdata\anaconda3\lib\site-packages (from pipreqs) (0.1.9)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from yarg->pipreqs) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (2.10)

!pipreqs

In [16]:
!pipreqs

WARNING: requirements.txt already exists, use --force to overwrite it